gpt:
  access: # wxid(暂只支持私聊)
    - wxid_xxxx1
    - wxid_xxxx2
    - wxid_xxxx3
  enable: true
gemini:
  access:
    - wxid_xxxx1
    - wxid_xxxx2
    - wxid_xxxx3
  enable: true
  token:  # Gemini's token
hitokoto:
  access:
    - wxid_xxxx1
    - wxid_xxxx2
    - wxid_xxxx3
  enable: true
menu:
  access:
    - wxid_xxxx1
    - wxid_xxxx2
    - wxid_xxxx3
  enable: true